name: Run pytest tests

on:
  workflow_call:
    inputs:
      python-versions:
        description: 'Supported python versions'
        default: '["3.10", "3.11", "3.12", "3.13", "3.14", "pypy-3.11"]'
        required: false
        type: string
      redis-versions:
        description: 'Redis versions'
        required: true
        type: string
      os:
        description: 'Operating system to run tests on'
        default: 'ubuntu-latest'
        required: false
        type: string
    secrets:
      codecov_token:
        description: 'Codecov token'
        required: false


jobs:
  redis:
    runs-on: ${{ inputs.os }}
    strategy:
      fail-fast: false
      matrix:
        python-version: ${{ fromJSON(inputs.python-versions) }}
        redis-version: ${{ fromJSON(inputs.redis-versions) }}
    env:
      OS: ${{ inputs.os }}
      PYTHON: ${{ matrix.python-version }}
      REDIS_VERSION: ${{ matrix.redis-version }}
    steps:
      - uses: actions/checkout@v6
      - name: Cache Redis builds
        uses: actions/cache@v5
        with:
          path: ~/redis
          key: redis-${{ hashFiles('.download-redis.sh') }}
      - name: Setup environment
        uses: fizyk/actions-reuse/.github/actions/pipenv-setup@v4.4.1
        with:
          python-version: ${{ matrix.python-version }}
          allow-prereleases: true
      - name: Install oldest supported versions
        uses: fizyk/actions-reuse/.github/actions/pipenv-run@v4.4.1
        with:
          command: pip install -r oldest/requirements.txt
      - name: Run test on Redis ${{ matrix.redis-version }}
        uses: fizyk/actions-reuse/.github/actions/pipenv-run@v4.4.1
        with:
          command: pytest -c pyproject.oldest.toml -p no:xdist --cov-report=xml --redis-exec=$HOME/redis/redis-${{ matrix.redis-version }}/src/redis-server
      - name: Run xdist test on Redis ${{ matrix.redis-version }}
        uses: fizyk/actions-reuse/.github/actions/pipenv-run@v4.4.1
        with:
          command: pytest -c pyproject.oldest.toml -n auto --max-worker-restart=0 --cov-report=xml:coverage-xdist.xml --redis-exec=$HOME/redis/redis-${{ matrix.redis-version }}/src/redis-server
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v5
        with:
          flags: linux,redis-${{ matrix.redis-version }}
          env_vars: OS,PYTHON,REDIS_VERSION
          fail_ci_if_error: false
          token: ${{ secrets.codecov_token }}
